/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pakages;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author kumbhar
 */
public class firstpage extends javax.swing.JFrame {

    /**
     * Creates new form firstpage
     */
    public firstpage() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RegisterNowButton = new javax.swing.JButton();
        PasswordFieldLoginpage = new javax.swing.JPasswordField();
        usernameTextfielld = new javax.swing.JTextField();
        CancelButtonFirstpage = new javax.swing.JButton();
        LoginButtonFirstPage = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ExitButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        showPasswordLoginPage = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RegisterNowButton.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        RegisterNowButton.setForeground(new java.awt.Color(27, 156, 252));
        RegisterNowButton.setText("Don't have an account? Register now !");
        RegisterNowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterNowButtonActionPerformed(evt);
            }
        });
        getContentPane().add(RegisterNowButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 300, -1));

        PasswordFieldLoginpage.setBackground(new java.awt.Color(240, 240, 240));
        PasswordFieldLoginpage.setFont(new java.awt.Font("Verdana", 2, 12)); // NOI18N
        PasswordFieldLoginpage.setForeground(new java.awt.Color(27, 156, 252));
        PasswordFieldLoginpage.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(PasswordFieldLoginpage, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 150, 20));

        usernameTextfielld.setBackground(new java.awt.Color(240, 240, 240));
        usernameTextfielld.setFont(new java.awt.Font("Verdana", 2, 12)); // NOI18N
        usernameTextfielld.setForeground(new java.awt.Color(27, 156, 252));
        usernameTextfielld.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        usernameTextfielld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTextfielldActionPerformed(evt);
            }
        });
        getContentPane().add(usernameTextfielld, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 150, 20));

        CancelButtonFirstpage.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        CancelButtonFirstpage.setForeground(new java.awt.Color(27, 156, 252));
        CancelButtonFirstpage.setText("Cancel");
        CancelButtonFirstpage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonFirstpageActionPerformed(evt);
            }
        });
        getContentPane().add(CancelButtonFirstpage, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, -1, 20));

        LoginButtonFirstPage.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        LoginButtonFirstPage.setForeground(new java.awt.Color(27, 156, 252));
        LoginButtonFirstPage.setText("Login");
        LoginButtonFirstPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonFirstPageActionPerformed(evt);
            }
        });
        getContentPane().add(LoginButtonFirstPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, 20));

        jLabel4.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(37, 204, 247));
        jLabel4.setText("Password :");
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        jLabel1.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(37, 204, 247));
        jLabel1.setText("User Id    :");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        ExitButton.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        ExitButton.setForeground(new java.awt.Color(27, 156, 252));
        ExitButton.setText("Exit");
        ExitButton.setInheritsPopupMenu(true);
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ExitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, -1, 20));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\kumbhar\\OneDrive\\Desktop\\sfghdghdghr.jpg")); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 1010, 660));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        showPasswordLoginPage.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        showPasswordLoginPage.setForeground(new java.awt.Color(37, 204, 247));
        showPasswordLoginPage.setText("show");
        showPasswordLoginPage.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        showPasswordLoginPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPasswordLoginPageActionPerformed(evt);
            }
        });
        jPanel1.add(showPasswordLoginPage);
        showPasswordLoginPage.setBounds(260, 230, 60, 20);

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\kumbhar\\OneDrive\\Desktop\\25496-removebg-preview.png")); // NOI18N
        jPanel1.add(jLabel9);
        jLabel9.setBounds(50, 20, 180, 130);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\kumbhar\\OneDrive\\Desktop\\69.jpg")); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(0, 0, 340, 810);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 370, 660));

        jPanel2.setBackground(new java.awt.Color(209, 204, 192));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Copperplate Gothic Bold", 2, 40)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("AnonymousHope");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(30, 7, 400, 80);

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 102, 51));
        jLabel7.setText("DONATE for BETTER TOMMOROW....");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(410, 50, 180, 20);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\kumbhar\\OneDrive\\Desktop\\69.jpg")); // NOI18N
        jLabel6.setText("dcbdvbdvbdbdvdcdccvdcvdccc");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(0, 0, 1370, 250);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 110));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        int a=JOptionPane.showConfirmDialog(null, "Do you really want to close application", "Select", JOptionPane.YES_NO_OPTION);
        if(a==0){
        System.exit(0);
        }
       
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void showPasswordLoginPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPasswordLoginPageActionPerformed
        if(showPasswordLoginPage.isSelected()){
            PasswordFieldLoginpage.setEchoChar((char)0);
        }else{
            PasswordFieldLoginpage.setEchoChar('*');
        }
    }//GEN-LAST:event_showPasswordLoginPageActionPerformed

    private void RegisterNowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterNowButtonActionPerformed
        DonorLoginPage frame= new DonorLoginPage();
        frame.setVisible(true);
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_RegisterNowButtonActionPerformed

    private void usernameTextfielldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTextfielldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTextfielldActionPerformed

    private void CancelButtonFirstpageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonFirstpageActionPerformed
        firstpage frame= new firstpage();
        frame.setVisible(true);
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_CancelButtonFirstpageActionPerformed

    private void LoginButtonFirstPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonFirstPageActionPerformed
       if(usernameTextfielld.getText().equals("admin") && PasswordFieldLoginpage.getText().trim().equals("admin")){
        setVisible(false);
        new AdminPage1().setVisible(true);
       }
    }//GEN-LAST:event_LoginButtonFirstPageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(firstpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(firstpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(firstpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(firstpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               firstpage frame=new firstpage();
                 frame.setVisible(true);
                 frame.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelButtonFirstpage;
    private javax.swing.JButton ExitButton;
    private javax.swing.JButton LoginButtonFirstPage;
    private javax.swing.JPasswordField PasswordFieldLoginpage;
    private javax.swing.JButton RegisterNowButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton showPasswordLoginPage;
    private javax.swing.JTextField usernameTextfielld;
    // End of variables declaration//GEN-END:variables
}
